name: release-dev

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - user-service
          - order-service
          - payment-service
          - product-service

    permissions:
      contents: write
      pull-requests: write
      security-events: write
      id-token: write 
      issues: write

    env:
      AWS_REGION: "us-east-1"
      ECR: "579871530627.dkr.ecr.us-east-1.amazonaws.com/test"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        working-directory: ${{ matrix.service }}
        run: |
          mvn clean package

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        working-directory: ${{ matrix.service }}
        run: |
          docker build \
            -f Dockerfile \
            -t $ECR/${{ matrix.service }}:${{ github.sha }} \
            .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR }}/${{ matrix.service }}:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push Image
        run: |
          docker push \
            $ECR/${{ matrix.service }}:${{ github.sha }}

      - name: Capture Digest
        id: digest
        run: |
          DIGEST=$(docker inspect \
            --format='{{index .RepoDigests 0}}' \
            $ECR/${{ matrix.service }}:${{ github.sha }})

          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Update GitOps Repo
        env:
          GH_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        run: |
          git clone https://github.com/Emmy-github-webdev/Kubernetes-argocd.git

          cd Kubernetes-argocd

          BRANCH=update-${{ matrix.service }}-${{ github.sha }}

          git checkout -b $BRANCH

          cd apps/${{ matrix.service }}/overlays/dev

          sed -i \
            "s/newTag:.*/newTag: ${{ github.sha }}/" \
            kustomization.yaml

          git config user.name "Emmy-github-webdev"
          git config user.email ${{ secrets.USER_EMAIL }}

          git add .

          git commit \
            -m "Promote ${{ matrix.service }} to ${{ github.sha }}"

          git push origin $BRANCH

          gh pr create \
            --title "Deploy ${{ matrix.service }}" \
            --body "Automated deployment PR"